CREATE TABLE [hrs].[tblDeclaration_OSR2019] (
    [DeclarationNumber]                 VARCHAR (6)     NOT NULL,
    [EmployerNumber]                    VARCHAR (6)     NOT NULL,
    [DeclarationDate]                   DATETIME        NOT NULL,
    [InstituteID]                       INT             NULL,
    [InstituteName]                     VARCHAR (255)   NULL,
    [CourseNumber]                      VARCHAR (8)     NULL,
    [CourseName]                        VARCHAR (255)   NULL,
    [StartDate]                         DATE            NULL,
    [EndDate]                           DATE            NULL,
    [CourseLocation]                    VARCHAR (100)   NULL,
    [ElearningSubscription]             VARCHAR (8)     NULL,
    [DeclarationAmount]                 DECIMAL (19, 4) NULL,
    [DeclarationAmountApproved]         DECIMAL (19, 4) NULL,
    [DeclarationStatus]                 VARCHAR (4)     NOT NULL,
    [StatusDescription]                 VARCHAR (100)   NULL,
    [ParentDeclarationNumber]           VARCHAR (6)     NULL,
    [PaymentRunDate]                    DATETIME        NULL,
    [PaymentRunID]                      INT             NULL,
    [DeclarationNumber_ReversalPayment] VARCHAR (6)     NULL,
    [PaymentRunDate_ReversalPayment]    DATETIME        NULL,
    [PaymentRunID_ReversalPayment]      INT             NULL,
    [OTIBDS_InstituteID]                INT             NULL,
    [OTIBDS_CourseID]                   INT             NULL,
    [OTIBDS_StatusCode]                 VARCHAR (4)     NULL,
    [OwnCourseDescription]              VARCHAR (255)   NULL,
    CONSTRAINT [PK_hrs_tblDeclaration_OSR2019] PRIMARY KEY CLUSTERED ([DeclarationNumber] ASC)
);

