
CREATE VIEW [crm].[viewEmployee_CRM]
AS
SELECT [Id]
      ,[otb_nummer_werknemer]
      ,[fullname]
      ,[pix_initials]
      ,[middlename]
      ,[lastname]
	  ,[gendercode]
      ,[otb_voorvoegselechtgenoot]
      ,[spousesname]
      ,[address1_line1]
      ,[address1_line2]
      ,[address1_line3]
      ,[address1_postalcode]
      ,[address1_country]
      ,[address1_composite]
      ,[birthdate]
      ,[otb_startdate]
      ,[otb_enddate]
  FROM [OTIBDYNAMICS365SYNC].[Dynamics365_PROD_sync].[dbo].[contact]
